version: 0.2

env:
  variables:
   imagen: wenance/branding-service
phases:
  pre_build:
    commands:
      - echo installing dependencies...
      - wget -O /bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x /bin/jq
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Servername :"$SERVER_NAME"
  build:
    commands:
      - LOCAL_GIT=`git log -1 | grep commit | sed 's/.* //g'`
      - echo $LOCAL_GIT
      - echo Build started on `date`
      - echo Building the Docker image...
      - export GITHUB_COMMIT_URL=https://api.github.com/repos/wenance/branding-service/commits/master\?access_token\=$GITHUB_TOKEN
      - export GITHUB_TAG_URL=https://api.github.com/repos/wenance/branding-service/tags\?access_token\=$GITHUB_TOKEN
      - export TAG_VERSION=$(curl -X GET $GITHUB_TAG_URL | jq -r .[0].name)
      - export LAST_COMMIT=$(curl -X GET $GITHUB_COMMIT_URL | jq -r .sha)
      - echo $TAG_VERSION
      - echo $LAST_COMMIT
      - docker build --build-arg ENVIRONMENT=$AMBIENTES --build-arg REACT_APP_APIPORT=81 --build-arg REACT_APP_ENV=$AMBIENTES --build-arg REACT_APP_BRAND=$BRANDS --build-arg REACT_APP_APIPORT=81 --build-arg SERVER_NAME="$SERVER_NAME" --build-arg REACT_APP_TAG_VERSION="$TAG_VERSION" --build-arg REACT_APP_LAST_COMMIT="$LAST_COMMIT" -t $imagen .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker images
      - docker tag $imagen $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:`docker images -q $imagen:latest`  
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:`docker images -q $imagen:latest`
      - printf '{"tag":"%s"}' `docker images -q $imagen:latest` > build.json
artifacts:
  files: build.json
cache:
  paths:
    - '/srv/src/node_modules/**/*'